Borrel reservations
KiOui/TOSTI pull request #172
Opened 2021-10-13 18:54 UTC by KiOui

This pull request adds a `borrel` application to TOSTI which replaces the functions of the [VoorraadCie](https://voorraadcie.nl/) website. The functions of the application include:

- Keeping track of people with a BasicBorrelBrevet
- Enabling people with a BasicBorrelBrevet to create ReservationRequests
- Enabling VoorraadCie members to respond to these ReservationRequests
- Enabling people with a BasicBorrelBrevet to track their ReservationRequests and see whether they are accepted
- Enabling people with a BasicBorrelBrevet to digitally hand in a BorrelForm
- Enabling VoorraadCie members to add and remove Products from the BorrelForm and their inventory

Closes #169

2021-10-17 06:39 UTC, KiOui commented
This needs to be changed as a whole when #174 is merged.

2022-02-22 09:54 UTC, JobDoesburg requested changes
I doubt if this venue calendar thing is the best way to separate modules. I think it is best to have borrel depend on the venue calendar app, and add one of those nice filters to display the kind of reservations that can be made for this calendar and add the buttons for it.

2022-02-22 09:54 UTC, JobDoesburg commented on website/borrel/selectors.py
> +    return models.ProductCategory.objects.all()
What is this? It seems like you're trying to create your own ProductManager and CategoryManager (which is nice, but just build it as such then)

2022-02-22 09:54 UTC, JobDoesburg commented on website/venues/selectors.py
> +    return models.Venue.objects.filter(active=True)
Make this a Manager

2022-02-22 10:01 UTC, JobDoesburg requested changes

2022-02-27 22:00 UTC, JobDoesburg commented
TODO: 

- [ ] Display form and non-form error messages correctly in the template
- [ ] Use correct success redirects and user-messages
- [ ] Improve page structure (menu items, buttons, etc)
- [ ] Implement the logic on when to use ReservationSubmission and ReservationUpdate views, when to show buttons and when to allow access to the view
- [ ] Implement something to check out submitted borrel lists as read only objects
- [ ] Deleting reservation items (hit the DELETE checkbox if 0 is entered)
- [ ] Fix the calendar (currently, nothing shows up in the calendar)
- [ ] Better link borrel and venue reservations
- [ ] Venue reservations page and explainer
- [ ] Give other people access to your borrel reservation
- [ ] Approval for changing reservations (if people change their reservation, this should be approved? Can they even change?)
- [ ] Notification emails

2022-03-07 14:11 UTC, KiOui commented
When reserving a Venue, I get this error:
<img width="890" alt="Schermafbeelding 2022-03-07 om 15 11 25" src="https://user-images.githubusercontent.com/38525109/157050316-c992a75e-a22b-4213-be81-e259358d934a.png">

2022-03-07 19:38 UTC, JobDoesburg approved these changes

2022-03-07 19:40 UTC, merged