Add announcements app to TOSTI.
KiOui/TOSTI pull request #353
Opened 2022-09-21 19:19 UTC by KiOui

This PR adds an announcement app to TOSTI. Announcements can be used to display messages on all of the TOSTI views.

Closes #347

2022-09-21 19:20 UTC, KiOui commented
Things still left to do:

- [ ] Add a way to close an announcement (also an API? endpoint).
- [ ] Add an API endpoint for retrieving the current announcements.
- [ ] Change the styling of the announcements such that they are distinct from the TOSTI header.

2022-10-01 12:02 UTC, JobDoesburg requested changes

2022-10-10 10:10 UTC, KiOui commented on website/announcements/models.py
> +    content = HTMLField(blank=False, max_length=500)
Maybe to include a link this would be nice.

2022-10-10 10:11 UTC, KiOui commented on website/announcements/models.py
> +    closable = models.BooleanField(default=True)
Not yet haha

2022-10-10 10:27 UTC, JobDoesburg commented on website/announcements/models.py
> +    content = HTMLField(blank=False, max_length=500)
agreed

2022-12-09 15:11 UTC, JobDoesburg commented on website/announcements/models.py
> +    def is_visible(self):
Maybe make a separate manager for this so you can query Announcements.visible

2022-12-09 15:12 UTC, JobDoesburg commented on website/announcements/static/announcements/js/announcements.js
> +}
newline

2022-12-10 15:06 UTC, JobDoesburg approved these changes

2022-12-11 10:47 UTC, merged