Add start of status screen and add new picked up button
KiOui/TOSTI pull request #520
Opened 2023-11-12 10:53 UTC by KiOui

Closes #519

2024-03-11 09:12 UTC, JobDoesburg reviewed
Looks good. Maybe we should put the status screen in a separate app though. I think that would help keep the orders app small (its already a bit too large)

2024-04-09 18:25 UTC, KiOui commented
Shall I merge this?

2024-04-10 07:31 UTC, JobDoesburg commented
@KiOui let's separate the status screen

2024-04-28 20:05 UTC, KiOui commented
Updated!

2024-04-29 08:27 UTC, JobDoesburg requested changes

2024-04-29 08:27 UTC, JobDoesburg commented on website/status_screen/urls.py
> +    path("<shift:shift>/", views.StatusScreen.as_view(), name="status"),
Maybe we should add a path with a venue, that automatically redirects to the currently open shift in that venue.

2024-04-29 08:27 UTC, JobDoesburg commented on website/status_screen/templates/status_screen/status_screen.html
> +                        `/api/v1/shifts/{{ shift.id }}/orders/?type=0&picked_up=false&ordering=ready_at`,
Is there maybe a way to use a {% url %} template tag here?

Like in https://github.com/JobDoesburg/yivi-portal/blob/51ced900cbda534e763f61403eb27eb5251740e6/schememanager/templates/yivi_request.html#L36

2024-04-29 08:27 UTC, JobDoesburg commented on website/status_screen/templates/status_screen/status_screen.html
> +                        `/api/v1/shifts/{{ shift.id }}/orders/?type=0&picked_up=false&ordering=ready_at`,
And similarly on all other places, actually

2024-05-21 07:28 UTC, JobDoesburg commented on website/status_screen/templates/status_screen/status_screen.html
> +                        `/api/v1/shifts/{{ shift.id }}/orders/?type=0&picked_up=false&ordering=ready_at`,
@KiOui status update?

2024-06-03 20:07 UTC, JobDoesburg approved these changes

2024-06-03 20:07 UTC, merged